import { Waybill } from './types';

export const INITIAL_WAYBILLS: Waybill[] = [
  {
    id: 'wb-001',
    idx: 1,
    clientName: '飞洋电商',
    fbaNo: 'FBA15G89Z',
    waybillNo: 'ANSU2026060101',
    destination: 'US-ONT8',
    declarationType: '买单报关',
    eta: '2026-06-25',
    productName: 'LED不锈钢日光灯 / 支架',
    etd: '2026-06-18',
    vesselVoyage: 'COSCO PEKING / 082W',
    declarationValue: 12500,
    attachments: 2,
    issueType: '无',
    courierCompany: '卡派',
    channel: '美森正班-定提',
    status: '入仓',
    clientRemark: '急单,请优先安排装柜',
    internalRemark: '已确认海关HS Code',
    warehouseCode: 'SZ01',
    zipCode: '91752',
    merchandiser: '张华',
    label: '重货',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z9999W90123456784',
    invoiceMade: '已制作',
    createTime: '2026-06-15',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-002',
    idx: 2,
    clientName: '智创科技',
    fbaNo: 'FBA15H77D',
    waybillNo: 'ANSU2026060102',
    destination: 'US-LAX9',
    declarationType: '一般贸易',
    eta: '2026-06-28',
    productName: '智能扫地机器人与原装配件',
    etd: '2026-06-19',
    vesselVoyage: 'EVER AIM / 025E',
    declarationValue: 48000,
    attachments: 4,
    issueType: '无',
    courierCompany: 'UPS',
    channel: '以星快船-限时达',
    status: '入仓',
    clientRemark: '内含锂电池,已贴电池标签',
    internalRemark: '电池资料已核实,通过安检',
    warehouseCode: 'SZ01',
    zipCode: '92337',
    merchandiser: '李明',
    label: '危险品',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z8888E90123447192',
    invoiceMade: '已制作',
    createTime: '2026-06-16',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '电池件',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '一号查验室'
  },
  {
    id: 'wb-003',
    idx: 3,
    clientName: '浩宇外贸',
    fbaNo: 'FBA15K21W',
    waybillNo: 'ANSU2026060103',
    destination: 'UK-LCY2',
    declarationType: '自单报关',
    eta: '2026-07-02',
    productName: '棉质提花床上四件套床单',
    etd: '2026-06-20',
    vesselVoyage: 'OOCL CHONGQING / 031W',
    declarationValue: 18900,
    attachments: 1,
    issueType: '资料缺失',
    courierCompany: 'FedEx',
    channel: '空运普货-超快线',
    status: '入仓',
    clientRemark: '客户急需上架，走快线',
    internalRemark: '报关委托书格式有误，待修改重传',
    warehouseCode: 'NB02',
    zipCode: '03130',
    merchandiser: '王晶',
    label: '普通货物',
    taxPayment: 'DDU',
    operator: '上海分公司',
    trackingNo: '774128912384',
    invoiceMade: '未制作',
    createTime: '2026-06-14',
    salesman: '赵磊',
    customerService: '刘芳',
    waybillType: '普货',
    hasInsurance: '无',
    hasDocs: '无',
    customsRoom: '无'
  },
  {
    id: 'wb-004',
    idx: 4,
    clientName: '云想服饰',
    fbaNo: 'FBA15J90M',
    waybillNo: 'ANSU2026060104',
    destination: 'DE-FRA3',
    declarationType: '买单报关',
    eta: '2026-07-06',
    productName: '夏季丝麻混纺连衣裙',
    etd: '2026-06-22',
    vesselVoyage: 'MSC OSCAR / 192N',
    declarationValue: 9200,
    attachments: 0,
    issueType: '无',
    courierCompany: '卡派',
    channel: '中欧班列-卡航',
    status: '出库',
    clientRemark: '按箱分拣贴标',
    internalRemark: '已出库交联运商',
    warehouseCode: 'SZ01',
    zipCode: '60306',
    merchandiser: '张华',
    label: '易碎品',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '3741829031',
    invoiceMade: '已制作',
    createTime: '2026-06-12',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-005',
    idx: 5,
    clientName: '恒通货运',
    fbaNo: 'FBA15L51A',
    waybillNo: 'ANSU2026060105',
    destination: 'US-LGB8',
    declarationType: '一般贸易',
    eta: '2026-06-24',
    productName: '户外露营折叠铝合金网椅',
    etd: '2026-06-15',
    vesselVoyage: 'COSCO PEKING / 082W',
    declarationValue: 34000,
    attachments: 3,
    issueType: '无',
    courierCompany: '卡派',
    channel: '美森正班-定提',
    status: '出仓',
    clientRemark: '加急，送港',
    internalRemark: '已报关，顺利放行',
    warehouseCode: 'SZ01',
    zipCode: '90802',
    merchandiser: '李明',
    label: '重货',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z9999W90123456799',
    invoiceMade: '已制作',
    createTime: '2026-06-10',
    salesman: '孙洋',
    customerService: '刘芳',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-006',
    idx: 6,
    clientName: '嘉诚数码',
    fbaNo: 'FBA15M11K',
    waybillNo: 'ANSU2026060106',
    destination: 'US-ONT8',
    declarationType: '买单报关',
    eta: '2026-06-20',
    productName: '无线五合一便携蓝色蓝牙音箱',
    etd: '2026-06-12',
    vesselVoyage: 'OOCL CHONGQING / 031W',
    declarationValue: 15600,
    attachments: 2,
    issueType: '无',
    courierCompany: 'UPS',
    channel: '以星快船-限时达',
    status: '运输',
    clientRemark: '请跟进开船状态',
    internalRemark: '目前海运中,预计按时到达',
    warehouseCode: 'SZ01',
    zipCode: '91752',
    merchandiser: '张华',
    label: '高价值',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z7777Y90123456722',
    invoiceMade: '已制作',
    createTime: '2026-06-08',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '电池件',
    hasInsurance: '有',
    hasDocs: '获得盖章',
    customsRoom: '无'
  },
  {
    id: 'wb-007',
    idx: 7,
    clientName: '博宇家居',
    fbaNo: 'FBA15N33B',
    waybillNo: 'ANSU2026060107',
    destination: 'US-MEM1',
    declarationType: '一般贸易',
    eta: '2026-06-10',
    productName: '简约北欧实木餐椅 / 办公桌板',
    etd: '2026-05-25',
    vesselVoyage: 'YANTIAN EXPRESS / 23A',
    declarationValue: 66000,
    attachments: 5,
    issueType: '无',
    courierCompany: '卡派',
    channel: '美森限时达',
    status: '签收',
    clientRemark: '无',
    internalRemark: 'POD已签回上传',
    warehouseCode: 'SZ01',
    zipCode: '38118',
    merchandiser: '李明',
    label: '超大件',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: 'ANSU-POD-33829',
    invoiceMade: '已制作',
    createTime: '2026-05-20',
    salesman: '赵磊',
    customerService: '刘芳',
    waybillType: '特殊货物',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-008',
    idx: 8,
    clientName: '凯旋玩具',
    fbaNo: 'FBA15P88C',
    waybillNo: 'ANSU2026060108',
    destination: 'UK-BHX4',
    declarationType: '买单报关',
    eta: '2026-06-18',
    productName: '儿童益智环保磁力片积木',
    etd: '2026-06-10',
    vesselVoyage: 'MSC OSCAR / 192N',
    declarationValue: 8800,
    attachments: 1,
    issueType: '查验扣货',
    courierCompany: 'DHL',
    channel: '中欧班列-卡航',
    status: '扣货',
    clientRemark: '海关查验协助',
    internalRemark: '深圳罗湖查验中，要求补充品牌授权书',
    warehouseCode: 'SZ01',
    zipCode: 'CV1 2FL',
    merchandiser: '王晶',
    label: '重货',
    taxPayment: 'DDU',
    operator: '深圳安速货运有限公司',
    trackingNo: '883921204',
    invoiceMade: '已制作',
    createTime: '2026-06-05',
    salesman: '孙洋',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '一号查验室'
  },
  {
    id: 'wb-009',
    idx: 9,
    clientName: '飞洋电商',
    fbaNo: 'FBA15Q22V',
    waybillNo: 'ANSU2026060109',
    destination: 'US-ONT8',
    declarationType: '买单报关',
    eta: '2026-06-29',
    productName: '合金制迷你自行车模型摆件',
    etd: '2026-06-20',
    vesselVoyage: 'EVER AIM / 025E',
    declarationValue: 14500,
    attachments: 2,
    issueType: '无',
    courierCompany: 'UPS',
    channel: '美森正班-定提',
    status: '入仓',
    clientRemark: '贴箱唛',
    internalRemark: '已贴标放入待装柜区',
    warehouseCode: 'SZ01',
    zipCode: '91752',
    merchandiser: '张华',
    label: '普货',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z9999W90123456888',
    invoiceMade: '已制作',
    createTime: '2026-06-15',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-010',
    idx: 10,
    clientName: '科迈尔配件',
    fbaNo: 'FBA15T44R',
    waybillNo: 'ANSU2026060110',
    destination: 'US-FTW1',
    declarationType: '一般贸易',
    eta: '2026-06-05',
    productName: '尼龙编织快充TypeC数据线',
    etd: '2026-05-20',
    vesselVoyage: 'YANTIAN EXPRESS / 23A',
    declarationValue: 24000,
    attachments: 3,
    issueType: '无',
    courierCompany: '卡派',
    channel: '以星快船',
    status: '取消',
    clientRemark: '由于客户生产延误取消本单配送',
    internalRemark: '已取消，无货，不产生计费',
    warehouseCode: 'SZ01',
    zipCode: '75241',
    merchandiser: '张华',
    label: '普通货物',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '无',
    invoiceMade: '未制作',
    createTime: '2026-05-18',
    salesman: '孙洋',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '无',
    hasDocs: '无',
    customsRoom: '无'
  },
  {
    id: 'wb-011',
    idx: 11,
    clientName: '智创科技',
    fbaNo: 'FBA15X99Z',
    waybillNo: 'ANSU2026060111',
    destination: 'US-ONT8',
    declarationType: '一般贸易',
    eta: '2026-06-27',
    productName: '红外智能额温枪 / 无线温湿度计',
    etd: '2026-06-18',
    vesselVoyage: 'COSCO PEKING / 082W',
    declarationValue: 38200,
    attachments: 3,
    issueType: '无',
    courierCompany: '卡派',
    channel: '美森正班-定提',
    status: '出库',
    clientRemark: '需要全木箱加固，防潮防震',
    internalRemark: '已进行防潮防震加固装箱',
    warehouseCode: 'SZ01',
    zipCode: '91752',
    merchandiser: '李明',
    label: '高价值',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z392019482103',
    invoiceMade: '已制作',
    createTime: '2026-06-13',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '医疗件',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  },
  {
    id: 'wb-012',
    idx: 12,
    clientName: '飞洋电商',
    fbaNo: 'FBA15Y88X',
    waybillNo: 'ANSU2026060112',
    destination: 'US-LAX9',
    declarationType: '买单报关',
    eta: '2026-07-03',
    productName: '不锈钢双层保温咖啡杯 500ml',
    etd: '2026-06-22',
    vesselVoyage: 'EVER AIM / 025E',
    declarationValue: 16800,
    attachments: 1,
    issueType: '无',
    courierCompany: '卡派',
    channel: '以星快船-限时达',
    status: '入仓',
    clientRemark: '贴标，加固外箱',
    internalRemark: '已完成贴标，等待装箱中',
    warehouseCode: 'SZ01',
    zipCode: '92337',
    merchandiser: '张华',
    label: '重货',
    taxPayment: 'DDP',
    operator: '深圳安速货运有限公司',
    trackingNo: '1Z89320149021',
    invoiceMade: '已制作',
    createTime: '2026-06-16',
    salesman: '王涛',
    customerService: '陈静',
    waybillType: '普货',
    hasInsurance: '有',
    hasDocs: '有',
    customsRoom: '无'
  }
];

export const STATIC_TABS_COUNTS = {
  '入仓': 27,
  '出库': 11,
  '出仓': 231,
  '运输': 26448,
  '签收': 347492,
  '扣货': 0,
  '取消': 20769,
  '全部': 374209
};
