export type WaybillStatus =
  | '已下单'
  | '已收货'
  | '已确认'
  | '转运中'
  | '已签收'
  | '退件'
  | '已取消'
  | '未确认'
  | '入仓'
  | '出库'
  | '出仓'
  | '运输'
  | '签收'
  | '扣货'
  | '取消';

export interface Waybill {
  id: string;
  idx: number;
  waybillNo: string;
  groupNo: string;
  mark: string;
  createTime: string;
  pickTime: string;
  outboundNo: string;
  clientName: string;
  extraFeeRequest: string;
  zipCode: string;
  operator: string;
  clientType: string;
  service: string;
  warehouseCode: string;
  country: string;
  trackingTemplate: string;
  pieces: string;
  declarationValue: number;
  declarationType: string;
  status: WaybillStatus;
  fbaNo: string;
  destination: string;
  tradeMode: string;
  eta: string;
  etd: string;
  vesselVoyage: string;
  productName: string;
  attachments: number;
  issueType: string;
  courierCompany: string;
  channel: string;
  clientRemark: string;
  internalRemark: string;
  warehouseCodeLegacy?: string;
  merchandiser: string;
  label: string;
  taxPayment: string;
  trackingNo: string;
  invoiceMade: string;
  salesman: string;
  customerService: string;
  waybillType: string;
  hasInsurance: string;
  hasDocs: string;
  customsRoom: string;
  pickWarehouse?: string;
  outTime?: string;
}

export interface FilterParams {
  keyword: string;
  groupNo: string;
  operator: string;
  clientName: string;
  waybillNo: string;
  warehouseCode: string;
  zipCode: string;
  country: string;
  service: string;
  status: string;
  fbaNo: string;
  channel: string;
  declarationType: string;
  tradeMode: string;
  clientRemark: string;
  internalRemark: string;
  salesman: string;
  customerService: string;
  productName: string;
  merchandiser: string;
  label: string;
  taxPayment: string;
  trackingNo: string;
  invoiceMade: string;
  destination: string;
  unlabelled: string;
  warehouseAttr: string;
  createTimeStart: string;
  createTimeEnd: string;
  pickTimeStart: string;
  pickTimeEnd: string;
  outTimeStart: string;
  outTimeEnd: string;
  pickWarehouse: string;
  waybillType: string;
  hasInsurance: string;
  hasDocs: string;
  customsRoom: string;
}
